# Generated by Django 5.2.8 on 2025-11-29 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "weekly_sales",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "customer_satisfaction",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cost_efficiency",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="marketing/documents/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Dashboard",
                "verbose_name_plural": "Marketing Dashboards",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MarketingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "weekly_sales",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_efficiency",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "staff_performance_score",
                    models.IntegerField(
                        default=0,
                        help_text="Score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "customer_satisfaction",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="marketing/reports/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Report",
                "verbose_name_plural": "Marketing Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StaffOpsBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("category", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "percentage_of_total",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of total (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="marketing/staff_ops_breakdown/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_ops_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff & Ops Breakdown",
                "verbose_name_plural": "Staff & Ops Breakdowns",
                "ordering": ["-date", "-amount"],
            },
        ),
        migrations.CreateModel(
            name="TeamPerformanceBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "staff_attendance",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sales_performance",
                    models.IntegerField(
                        default=0,
                        help_text="Performance score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "inventory_status",
                    models.IntegerField(
                        default=0,
                        help_text="Status percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "issues_complaints",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="marketing/team_performance/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_performance_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team & Performance Breakdown",
                "verbose_name_plural": "Team & Performance Breakdowns",
                "ordering": ["-date"],
            },
        ),
    ]
