# Generated by Django 5.2.5 on 2025-10-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('manager', 'Manager'), ('franchisee', 'Franchisee'), ('admin', 'Admin')], default='operator', max_length=15),
        ),
    ]
