# Generated by Django 5.2.5 on 2025-10-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_alter_userprofile_updated_at'),
    ]

    operations = [
    ]
