# Generated by Django 5.2.5 on 2025-10-29 10:55

from django.db import migrations


def verify_admin_users(apps, schema_editor):
    """Set is_verified=True for all users with admin role"""
    CustomUser = apps.get_model('authentications', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(is_verified=True)


def reverse_verify_admin_users(apps, schema_editor):
    """Reverse operation - this doesn't change verification status"""
    # We don't want to automatically unverify admin users when reversing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_auto_20251029_1555'),
    ]

    operations = [
        migrations.RunPython(verify_admin_users, reverse_verify_admin_users),
    ]
