# Generated by Django 5.2.7 on 2025-11-01 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_verify_admin_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name_dba', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, choices=[('America/Los_Angeles', 'America/Los_Angeles'), ('America/Denver', 'America/Denver'), ('America/Chicago', 'America/Chicago'), ('America/New_York', 'America/New_York')], max_length=50, null=True)),
                ('service_model', models.CharField(blank=True, choices=[('QSR', 'QSR'), ('Fast Casual', 'Fast Casual'), ('Full Service', 'Full Service'), ('Cafe', 'Cafe'), ('Bar', 'Bar'), ('Catering', 'Catering'), ('Ghost Kitchen', 'Ghost Kitchen')], max_length=50, null=True)),
                ('is_franchise', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('franchise_brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('locations_owned_operated', models.TextField(blank=True, null=True)),
                ('region_market', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_url', models.URLField(blank=True, null=True)),
                ('menu_file', models.FileField(blank=True, help_text='Menu file upload', null=True, upload_to='onboarding/menus/%Y/%m/')),
                ('estimated_instore_sales_last_month', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_online_3p_sales_last_month', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_instore_sales_last_12_months', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_online_3p_sales_last_12_months', models.PositiveIntegerField(blank=True, null=True)),
                ('foh_employees', models.TextField(blank=True, null=True)),
                ('boh_employees', models.TextField(blank=True, null=True)),
                ('pay_cadence', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, help_text='Document file upload', null=True, upload_to='onboarding/documents/%Y/%m/')),
                ('monthly_marketing_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('key_policies', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progresses',
            },
        ),
    ]
