# Generated by Django 5.2.8 on 2025-11-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0009_onboardingprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("operations", "Operations"),
                    ("marketing manager", "Marketing Manager"),
                    ("executive", "Executive"),
                    ("admin", "Admin"),
                ],
                default="operations",
                max_length=20,
            ),
        ),
    ]
