# Generated by Django 5.2.8 on 2025-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0011_calendarevent_subscription_userdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_payment_intent",
            field=models.CharField(
                blank=True,
                help_text="Stripe Payment Intent ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, help_text="Stripe Price ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Checkout Session ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
