# Generated by Django 5.2.8 on 2025-11-29 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOperationBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "in_store_orders",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "online_orders",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "third_party_delivery",
                    models.IntegerField(
                        default=0,
                        help_text="3PD - Third Party Delivery",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("discounts_and_refunds", models.IntegerField(default=0)),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="operations/daily_breakdown/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_operation_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Operation Breakdown",
                "verbose_name_plural": "Daily Operation Breakdowns",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialPerformanceBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("category", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "percentage_of_total",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of total (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="operations/financial_breakdown/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_performance_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Performance Breakdown",
                "verbose_name_plural": "Financial Performance Breakdowns",
                "ordering": ["-date", "-amount"],
            },
        ),
        migrations.CreateModel(
            name="OperationDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "today_sales",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "staff_attendance",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("labor_cost_vs_budget", models.IntegerField(default=0)),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="operations/documents/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Dashboard",
                "verbose_name_plural": "Operation Dashboards",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OperationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "today_sales",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "order_completed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "delivery_on_time_rate",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "shift_attendance",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="operations/reports/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Report",
                "verbose_name_plural": "Operation Reports",
                "ordering": ["-date"],
            },
        ),
    ]
