# Generated by Django 5.2.8 on 2025-11-29 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHealthBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "sales_revenue",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expenses_costs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "marketing_campaigns_roi",
                    models.IntegerField(
                        default=0, help_text="Return on Investment percentage"
                    ),
                ),
                (
                    "risk_loss",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="executive/business_health/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_health_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Health Breakdown",
                "verbose_name_plural": "Business Health Breakdowns",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_sales_revenue",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("net_profit", models.IntegerField(default=0)),
                (
                    "store_growth_comparison",
                    models.IntegerField(
                        default=0, help_text="Growth percentage comparison"
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="executive/documents/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive Dashboard",
                "verbose_name_plural": "Executive Dashboards",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_revenue",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_outlets",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "branches_meeting_sales_target",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "active_promotions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="executive/reports/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive Report",
                "verbose_name_plural": "Executive Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialPerformanceBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("category", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "percentage_of_total",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of total (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_document",
                    models.FileField(
                        blank=True,
                        help_text="Document uploaded by user for AI extraction",
                        null=True,
                        upload_to="executive/financial_breakdown/%Y/%m/",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_financial_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Performance Breakdown",
                "verbose_name_plural": "Financial Performance Breakdowns",
                "ordering": ["-date", "-amount"],
            },
        ),
    ]
